name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: |
          11
          17
    - uses: gradle/wrapper-validation-action@v1
    - name: Build with Gradle
      run: ./gradlew build --warning-mode=summary
    - name: Sonar analysis
      run: |
        ./gradlew sonarqube -Dsonar.token=$SONAR_TOKEN \
                            --warning-mode=summary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      if: always()
      with:
        report_paths: '**/build/test-results/*/TEST-*.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}
