name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matrix-build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17, 21]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-java-${{ matrix.java }}
      cancel-in-progress: true
    name: "Build with Java ${{ matrix.java }}"
    env:
      DEFAULT_JAVA: 11
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: |
          11
          17
          21
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
    - name: Build with Java ${{ matrix.java }}
      run: ./gradlew build --info --warning-mode=summary -PjavaVersion=${{ matrix.java }}
    - name: Sonar analysis
      if: ${{ env.DEFAULT_JAVA == matrix.java && env.SONAR_TOKEN != null }}
      run: |
        ./gradlew sonarqube -Dsonar.token=$SONAR_TOKEN -PjavaVersion=${{ matrix.java }} \
                            --info --warning-mode=summary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    needs: matrix-build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build successful"
      