name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  matrix-build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 17, 21]
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-java-${{ matrix.java }}
      cancel-in-progress: true
    name: "Build with Java ${{ matrix.java }}"
    env:
      DEFAULT_JAVA: 11

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: temurin
        java-version: |
          11
          17
          21
    - uses: gradle/wrapper-validation-action@v1
    - name: Build with Java ${{ matrix.java }}
      run: ./gradlew build --info --warning-mode=summary -PjavaVersion=${{ matrix.java }}
    - name: Sonar analysis
      if: ${{ env.DEFAULT_JAVA == matrix.java && env.SONAR_TOKEN != null }}
      run: |
        ./gradlew sonarqube -Dsonar.token=$SONAR_TOKEN -PjavaVersion=${{ matrix.java }} \
                            --info --warning-mode=summary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      if: always()
      with:
        report_paths: '**/build/test-results/*/TEST-*.xml'
        github_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    needs: matrix-build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build successful"
      